version: 2.1

orbs:
  vonage-sms: dapper/vonage-sms@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: dapper/vonage-sms
          context: publish
          requires: [hold-for-dev-publish]
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: publish
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-sms
      - test-facebook
      - test-whatsapp
      - test-viber
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: dapper/vonage-sms
          context: publish
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - test-sms
            - test-facebook
            - test-whatsapp
            - test-viber
          filters:
            branches:
              only: master

jobs:
  test-sms:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - vonage-sms/sms:
          message: "Hello, world! ($CIRCLE_BUILD_ID)"
          vonage_number: "$VONAGE_SMS_TEST_SENDER"
          recipient: "$VONAGE_SMS_TEST_RECIPIENT"
  test-facebook:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - vonage-sms/facebook-messenger:
          message: "Hello, world! ($CIRCLE_BUILD_ID)"
          sender_id: "$VONAGE_FB_TEST_SENDER"
          recipient: "$VONAGE_FB_TEST_RECIPIENT"
  test-whatsapp:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - vonage-sms/whatsapp:
          message: "Hello, world! ($CIRCLE_BUILD_ID)"
          vonage_number: "$VONAGE_WHATSAPP_TEST_SENDER"
          recipient: "$VONAGE_WHATSAPP_TEST_RECIPIENT"
  test-viber:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - vonage-sms/viber:
          message: "Hello, world! ($CIRCLE_BUILD_ID)"
          sender_id: "$VONAGE_VIBER_TEST_SENDER"
          recipient: "$VONAGE_VIBER_TEST_RECIPIENT"
